#lang racket
(define (smallest-divisor a)
  (smallest-divisor-iter a 2)
  )
(define (smallest-divisor-iter a result)
  (cond ((> (* result result) a) a)
        ((= (remainder a result) 0) result)
        (else (smallest-divisor-iter a (+ result 1)))))
(display (smallest-divisor 199))
(newline)
(display (smallest-divisor 1999))
(newline)
(display (smallest-divisor 199999))
(newline)