#lang racket
(define (deriv g) 
  (lambda (x)
    (/ (- (g (+ x dx)) (g x)) dx)))
(define dx 0.000001)
(define (cube x) (* x x x))
(define (newton-transform g)
  (lambda (x)
    (- x (/ (g x) ((deriv g) x)))))
(define (cubic a b c)
  (lambda (x) (+ (cube x) (* a x x) (* b x) c)))
(define (newtons-method g guess)
  (fixed-point (newton-transform g) guess))
(define (average x y) (/ (+ x y) 2))
(define tolerance 0.000001)
(define (fixed-point f first-guess)
  (define (close-enough? v1 v2)
    (< (abs (- v1 v2)) tolerance))
  (define (try guess)
    (let ((next (f guess)))
      (if (close-enough? guess next)
          next
          (try next))))
  (try first-guess))